-- BODEN MOBİL: ortak merkezi veri şeması
create table if not exists public.boden_shared_store (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.boden_shared_store enable row level security;

drop policy if exists "public read" on public.boden_shared_store;
drop policy if exists "public insert" on public.boden_shared_store;
drop policy if exists "public update" on public.boden_shared_store;
drop policy if exists "public delete" on public.boden_shared_store;

create policy "public read" on public.boden_shared_store for select using (true);
create policy "public insert" on public.boden_shared_store for insert with check (true);
create policy "public update" on public.boden_shared_store for update using (true) with check (true);
create policy "public delete" on public.boden_shared_store for delete using (true);

grant select, insert, update, delete on public.boden_shared_store to anon, authenticated;
grant usage, select on sequence public.boden_shared_store_id_seq to anon, authenticated;

create or replace function public.boden_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists boden_touch_updated_at on public.boden_shared_store;
create trigger boden_touch_updated_at before update on public.boden_shared_store
for each row execute function public.boden_touch_updated_at();
